import { Della_Respira } from "next/font/google";
import "./globals.css";

// Removed the unavailable 500, 600, and 700 weights
const dellaRespira = Della_Respira({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata = {
  title: "Lasya's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dellaRespira.className} forced-bold`}>{children}</body>
    </html>
  );
}
